security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        user_email_provider:
            entity:
                class: App\Entity\User
                property: email
        user_username_provider:
            entity:
                class: App\Entity\User
                property: username
        user_provider:
            chain:
                providers: [ user_email_provider, user_username_provider ]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: user_provider
            form_login:
                login_path: app_user_login
                check_path: app_user_login
            logout:
                path: app_user_logout
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER];
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }


